### ISSUE TITLE
Svg logo for Cypress testing framework and Reddit

### ISSUE THREAD

**Issue by louisgituhi** [pheralb/svgl#118]
A request for cypress testing framework and reddit logo

**Comment by wilmer2000** [comment]
@louisgituhi PR created https://github.com/pheralb/svgl/pull/120

**Comment by louisgituhi** [comment]
Wow. That was fast 💯. Anyway this is an awesome project. I discovered it through X

**Comment by wilmer2000** [comment]
I guess this issue should be closed ;)
