### ISSUE TITLE
seems https://svgl.vercel.app/ can not be accessed

### ISSUE THREAD

**Issue by DamonsJ** [pheralb/svgl#122]
can not open this website 
https://svgl.vercel.app/ 

give me this error:

NET::ERR_CERT_COMMON_NAME_INVALID

**Comment by sujjeee** [comment]
Still getting error??

might be issue with DNS read this https://github.com/orgs/vercel/discussions/4112

**Comment by DamonsJ** [comment]
yes , same error !
try edge and chrome and safari
got same error

**Comment by manish2022-creator** [comment]
Is this error got solved or still their?

**Comment by manish2022-creator** [comment]
![Screenshot 2023-12-16 235708](https://github.com/pheralb/svgl/assets/77712914/7b35b96c-550d-460f-9e12-b22e0168b299)
Its opening. You should please check it out again @DamonsJ

**Comment by sujjeee** [comment]
@DamonsJ check your DNS settings !

or try to access it with different ISP

**Comment by davidho0403** [comment]
@DamonsJ A new domain is available here [svgl.app](https://svgl.app/)

**Comment by DamonsJ** [comment]
> @DamonsJ A new domain is available here [svgl.app](https://svgl.app/)

Thanks!
This one works for me!
