### ISSUE TITLE
Add a feature to switch between Logo and Wordmark

### ISSUE THREAD

**Issue by davidho0403** [pheralb/svgl#128]
## Description
Some logos have two versions: a pure logo and a logo with text. I think it would be useful to have a feature that allows switching between the two.

## Example
<img width="253" alt="image" src="https://github.com/pheralb/svgl/assets/75478661/7d5f4c2b-6aaf-4e25-be22-fa5389a06924">
<img width="254" alt="image" src="https://github.com/pheralb/svgl/assets/75478661/86f3c509-653a-4334-9c4b-af621d02baf5">

**Comment by manish2022-creator** [comment]
Does this issue had been solved or its still their? If its still their I am going to solve it please reply for further activities

**Comment by pheralb** [comment]
I love the idea 👀🚀✨

**Comment by davidho0403** [comment]
Implemented in #208, closed it 🚀.
