### ISSUE TITLE
[Feat]: 1 svg can have multiple categories

### ISSUE THREAD

**Issue by jvngarcia** [pheralb/svgl#142]
For example Wordpress is a software and a CMS

![image](https://github.com/pheralb/svgl/assets/66430217/d123f5e5-89ed-4b2d-b8ab-eba53a209732)

**Comment by jvngarcia** [comment]
Can I help with this or have you already worked on something similar?

**Comment by jvngarcia** [comment]
https://github.com/pheralb/svgl/pull/143

**Comment by pheralb** [comment]
Ready 🚀
https://github.com/pheralb/svgl?tab=readme-ov-file#-getting-started
