### ISSUE TITLE
[Request]: Add bluesky

### ISSUE THREAD

**Issue by jacobdalamb** [pheralb/svgl#155]
- **Title**: bluesky;
- **Category**: social
- **Source (.svg)**: https://bsky.app/static/apple-touch-icon.png (couldn't find .svg file in source code)
- **Website**: https://blueskyweb.xyz/blog/12-21-2023-butterfly

## Checklist (required):

- [x] #739

**Comment by wilmer2000** [comment]
FYI: I've found the SVG logo into the HTML code in this page https://bsky.app/

**Comment by sujjeee** [comment]
https://github.com/pheralb/svgl/commit/cc9904d9617e72ddf2c1b2ac7b88325607a1cbb8
Done 👍
