### ISSUE TITLE
Permission to use part of your code

### ISSUE THREAD

**Issue by marpeand** [pheralb/svgl#161]
Hi! I'd like to use part of your Tailwind code to use in my personal side project. Would you mind granting me permission for this? thank you.

**Comment by sujjeee** [comment]
@marpeand  The project is completely open-source and has an MIT license, meaning it's copyright-free. You can use it in your projects without any copyright issues.

**Comment by marpeand** [comment]
Thanks! I completely forgot the license. Sorry.
