### ISSUE TITLE
Flask

### ISSUE THREAD

**Issue by j0k3rD** [pheralb/svgl#201]
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" fill="#000000" version="1.1" width="800px" height="800px" viewBox="0 0 512 512" enable-background="new 0 0 512 512" xml:space="preserve">

<g id="e6c6b53d3c8160b22dad35a0f7103ecc">

<path display="inline" fill-rule="evenodd" clip-rule="evenodd" d="M145.973,124.482c-1.766-15.299,12.003-8.814,10.244,0.41   C153.633,127.35,148.86,125.334,145.973,124.482z M162.363,121.613c3.468-0.354,6.774-0.874,7.787-3.687   c-4.797-2.957-11.965,4.339-9.016,7.787C162.771,125.574,161.323,122.351,162.363,121.613z M116.468,131.038   c2.888-1.343,7.633-0.836,9.016-3.687c-8.596-2.994-24.076-0.784-26.638,4.917C105.399,131.863,110.879,126.663,116.468,131.038z    M97.207,132.679c-1.862-0.391-2.58,1.724-1.638,2.867C97.024,135.498,97.218,134.19,97.207,132.679z M92.699,140.875   c-0.262-3.909-9.718-7.03-10.653-1.639C82.864,142.297,90.491,144.266,92.699,140.875z M76.719,137.188   c-1.953,0.091-2.957,1.142-4.099,2.048C74.106,140.102,77.398,139.792,76.719,137.188z M71.803,148.25   c7.218-0.507,9.415,6.13,15.569,5.327C88.519,146.433,73.837,136.606,71.803,148.25z M169.329,183.899   c-2.152-7.142,4.438-13.272,0.409-18.851c-5.578,0.445-10.402,26.334-2.458,26.23c5.704-0.079,7.715-15.738,8.194-20.898   C171.298,172.754,173.117,181.132,169.329,183.899z M100.896,181.034c0.124-1.083-0.568-1.347-1.639-1.233   C99.284,180.907,100.193,181.772,100.896,181.034z M120.976,192.917c0.079-2.539-0.021-4.897-2.048-5.327   c-1.543-0.175-1.451,1.281-2.46,1.641C117.031,191.397,118.175,192.988,120.976,192.917z M101.306,206.031   c7.857,0.884,13.118,6.552,20.489,6.554c-5.878-3.957-11.985-7.683-21.309-8.194C100.189,205.509,101.3,205.216,101.306,206.031z    M163.183,212.177c-0.611-2.805-1.828-5.005-3.277-6.968C160.439,208.089,161.174,210.768,163.183,212.177z M118.106,221.191   c-5.143-6.882-13.337-12.879-22.537-14.343C96.868,217.841,109.088,217.92,118.106,221.191z M104.175,223.648   c-3.512-5.911-9.533-9.317-16.803-11.471C91.458,217.255,95.201,224.823,104.175,223.648z M85.324,217.914   c1.399,2.429,4.916,4.912,4.099,8.195c-3.593-1.05-5.34-3.949-9.016-4.917c1.952,2.711,9.402,14.729,13.931,14.345   c2.891-0.25,4.198-3.441,3.688-8.606C95.811,222.176,88.76,220.078,85.324,217.914z M106.223,228.568   c0.911,2.505,1.231,5.598,4.509,5.735C110.174,231.448,108.506,229.699,106.223,228.568z M103.354,229.799   c-1.528-0.167-2.403,0.324-2.457,1.636c0.459,0.09,0.638,0.454,0.818,0.819C103.025,232.203,103.521,231.327,103.354,229.799z    M173.427,239.222c0.427-2.316,0.861-6.778,0-9.016C172.901,232.508,170.922,237.686,173.427,239.222z M144.743,230.616   c0.313,2.422-0.858,6.323,1.229,6.97C146.063,235.793,146.481,231.755,144.743,230.616z M164.002,240.042   c-1.189-1.054-2.895,0.539-3.688-0.408c-0.838-2.713-0.491-6.61-2.868-7.787c-0.271,0-0.546,0-0.818,0   c-3.375,6.99-3.042,22.007,2.867,25.814c1.116,1.891,1.225,4.787,4.098,4.92c2.362-1.875,2.942-5.524,3.279-9.428   C161.743,252.076,166.521,243.235,164.002,240.042z M176.297,244.547c0.505-3.628,3.607-8.905,1.229-12.7   C176.741,235.438,175.255,240.499,176.297,244.547z M104.175,247.83c0.653-1.873,0.14-5.05-1.23-6.148   C101.989,243.476,101.433,247.608,104.175,247.83z M111.55,249.467c1.655,1.077,1.782,3.68,4.099,4.098   C118.532,249.885,113.063,243.399,111.55,249.467z M181.623,257.661c0.003,1.256-1.643,2.974-0.409,4.097   C181.451,260.743,182.698,258.631,181.623,257.661z M185.31,273.643c-0.017-1.892,0.231-4.05-0.818-4.915   C184.308,270.187,183.227,273.418,185.31,273.643z M133.269,290.447c0.243,1.526,0.492,3.057,2.048,3.277   C136.322,292.318,135.58,289.828,133.269,290.447z M151.709,292.497c0.57,1.082,2.208,3.231,3.277,2.454   C154.038,294.252,152.944,291.55,151.709,292.497z M190.637,297.005c-1.151,4.879,1.574,9.324,3.689,12.293   C195.192,304.541,195.111,297.729,190.637,297.005z M200.884,328.552c0.619-1.239,0.838-5.057-0.41-5.73   C199.395,324.302,198.433,327.845,200.884,328.552z M219.32,348.226c-0.593-3.011-2.952-6.263-5.325-6.15   C214.825,345.069,214.969,348.754,219.32,348.226z M223.012,353.961c0.017,1.896-0.229,4.059,0.818,4.915   C223.883,356.917,223.855,355.029,223.012,353.961z M87.782,354.372c0.006,1.501,0.809,2.196,1.641,2.869   C89.259,355.898,89.067,354.593,87.782,354.372z M237.764,376.907c-1.009-7.727-5.073-12.404-10.244-15.977   C228.26,368.927,232.179,373.755,237.764,376.907z M303.74,417.478c-0.249-0.232-1.946-0.956-2.05,0   C302.306,417.952,303.416,418.917,303.74,417.478z M511.501,447.802c0,1.506,0,3.003,0,4.508c-0.666,1.385-0.882,3.215-1.231,4.916   c-11.395,7.318-32.803,4.624-42.209,13.935c-16.497-8.887-31.829,5.111-49.17,6.559c-2.865,0.236-6.051-0.241-9.021,0   c-10.246,0.827-20.252,3.223-30.731,4.096c-10.745,0.895-21.512,1.551-32.781,2.05c-4.101,0-8.196,0-12.293,0   c-50.825-2.669-101.077-9.506-138.508-26.228c-18.661-8.338-35.838-18.567-51.632-30.735c-15.37-11.835-31.147-24.993-42.21-39.747   c-11.778-15.711-23.562-30.989-34.012-48.352c-10.081-16.759-19.504-34.412-27.864-54.094   c-8.247-19.408-14.123-38.613-19.672-62.287c-3.627-15.484-7.455-33.015-13.932-47.534c-2.522-5.654-5.458-10.282-5.736-15.574   c0-1.227,0-2.46,0-3.687c2.021-17.212,15.407-27.203,31.143-31.965c3.94-1.191,7.771-2.329,11.474-4.508   c0.241-0.139,2.602-0.38,1.641-1.638c-7.011-1.687-12.779,8.635-20.489,5.737c-6.845-2.574-2.904-13.172,4.508-16.391   c3.46-1.503,10.33-1.894,13.521-3.688c5.502-3.092,7.999-9.625,6.968-15.572c-0.611-3.514-4.258-5.364-4.098-8.196   c0.224-3.949,7.285-7.383,10.653-9.835c4.121-2.999,8.999-6.745,8.606-11.474c-0.414-4.94-6.224-6.514-9.016-10.244   C51.027,42,50.332,33.25,57.458,29.821c7.471-3.595,21.39-1.636,22.949,7.787c1.374,8.305-4.522,11.469-2.051,17.62   c4.604,11.446,40.409-6.672,31.556,17.212c7.874,12.343,38.645,1.784,39.339,21.309c12.834,0.258,18.732,9.997,29.094,13.933   c2.777,1.054,6.084,1.054,9.016,2.048c17.476,5.94,39.132,12.312,46.305,29.095c-6.482,4.367-15.328,1.443-22.946-1.229   c-6.627-2.327-16.287-6.935-22.949-4.099c-6.605,2.813-6.252,14.098-5.327,25.405c2.46,30.102,3.903,61.151,8.194,88.104   c5.993,37.623,18.803,67.756,36.883,91.384c17.49,22.859,38.037,46.796,64.743,63.518c22.535,14.105,47.853,25.234,79.91,32.37   c4.754,1.061,10.501,3.377,13.112,2.869c3.871-0.744,12.201-12.001,15.166-14.75c7.049-6.554,16.534-15.724,26.631-7.789   c-1.372,10.925-11.161,13.433-13.523,23.362c6.071,3.863,12.509,0.366,20.082,0.815c8.812,0.524,15.569,5.577,22.951,4.508   c4.711-0.682,7.069-4.191,10.653-6.554C475.388,448.642,506.78,433.147,511.501,447.802z M422.574,417.478   c-0.174-1.322,0.541-3.543-0.818-3.684C420.574,414.393,419.406,418.16,422.574,417.478z M216.457,128.99   c4.014,2.404,7.548,5.292,11.063,8.199c2.116-6.231-3.957-10.217-11.063-9.837C216.457,127.896,216.457,128.443,216.457,128.99z    M326.688,431.001c1.563,0.329,2.694,0.641,2.869-1.227C328.097,429.679,327.104,430.045,326.688,431.001z M270.136,394.938   c-0.138,1.93,3.755,1.967,4.512,1.639C274.007,395.296,272.065,393.633,270.136,394.938z M260.301,387.154   c0.682,0.69,2.407,0.324,3.688,0.411c0.137-1.501-0.458-2.278-0.819-3.281C261.016,384.048,260.421,385.361,260.301,387.154z    M181.623,219.55c-1.112-0.942-1.919,0.784-2.459,0c1.335-10.166,3.48-25.818-0.819-34.418c-1.063-0.928-2.745,0.326-3.277-0.412   c2.861-6.83,4.793-21.075,3.687-29.504c-0.389-2.971-1.932-8.255-3.687-9.425c-4.41-2.936-8.423,1.576-11.476,2.459   c-1.921,0.56-4.057,0.16-6.146,0.408c-8.263,0.996-17.031,3.46-22.537,6.146c2.87,1.913,6.938,2.624,8.194,6.146   c-7.14-0.505-12.71-2.583-18.851-4.096c0.655,9.245-10.683,6.348-17.619,6.968c2.396,0.052,2.78,1.21,2.869,2.867   c0.285,5.439-17.613,11.885-23.768,7.789c-8.779,7.078,3.863,14.308,3.278,23.358c-1.726,1.279-2.523,3.485-4.098,4.913   c-8.725,0.212-17.902,1.967-16.394,11.066c-1.179-0.688-3.039-1.147-4.508-0.412c-2.23,5.745,1.514,11.981,6.559,13.116   c1.271-0.37,1.567-1.711,3.278-1.639c11.396,2.179,15.408,9.737,14.753,24.174c-0.114,2.486,0.133,5.73-1.639,7.379   c-6.467-0.443-12.463-16.405-2.05-16.8c-2.497-3.674-4.388-9.155-9.016-9.018c-5.305,0.158-7.686,8.542-11.474,11.475   c5.46,3.017,18.283,11.343,7.785,16.801c5.197,0.779,8.097,2.84,10.244,5.734c3.578,4.832,3.464,12.072,6.148,15.985   c5.431,7.922,8.298-7.106,14.75-0.823c1.524,0.524-0.671-1.48-0.819-1.635c-5.535-5.976-13.977-10.874-17.21-18.031   c2.485-1.139,5.816,0.104,8.194,0.408c0.94-4.814-2.405-10.262-1.229-13.936c0.847-2.634,2.41-1.474,4.099-2.456   c0.993-0.578,0.216-2.73,2.05-2.048c-0.011,5.626-3.401,15.094,0.407,19.259c5.561,0.998,7.167-8.565,11.886-8.605   c2.636-0.023,5.127,4.617,6.965,6.966c2.208,2.819,5.209,6.283,4.508,9.423c-1.476,6.62-12.594,1.58-16.391-1.23   c2.314,9.186,16.553,10.612,17.21,22.543c0.075,1.331-0.597,3.031-0.409,4.504c0.805,6.296,6.676,10.975,12.702,6.97   c0.886,2.258,1.002,5.285,3.281,6.146c1.996-1.688,1.287-6.089,2.457-8.608c7.15,1.497,10.883,4.94,13.112,10.654   c1.104,2.827,0.819,8.067,5.327,8.196c0.69-6.986-4.784-11.315-5.735-18.031c3.673,5.926,16.922,12.338,16.392,21.72   c-0.352,6.188-7.706,6.861-14.753,7.785c6.716,2.308,9.529,9.83,16.801,12.292c1.954,0.666,4.464,0.096,6.556,0.823   c5.321,1.851,13.829,12.759,11.476,19.67c-11.338,5.714-20.184-9.73-32.784-9.423c5.313,6.774,14.004,9.028,21.309,12.293   c7.862,3.51,15.734,7.106,23.358,10.653c17.972,8.359,30.447,19.296,42.209,33.193c-8.161,4.45-32.897-2.952-18.031-8.2   c-5.171-0.175-10.644-3.418-15.164-1.634c2.396,15.636,22.968,13.095,38.522,15.569c-1.416,2.682-3.412,4.786-4.919,7.377   c1.199,0.707,2.856,0.965,4.919,0.819c-0.996,1.597-3.589,1.601-3.69,4.096c1.992,2.653,5.935,3.356,8.606,5.327   c10.531-7.552,11.712,9.581,18.44,9.835c6.358,0.237,7.577-8.899,13.936-9.835c-1.598,3.323-4.725,5.111-6.146,8.608   c6.226-1.505,8.001-4.857,13.107-6.15c18.298-4.629,33.298,10.612,48.355,12.297c5.414,0.603,10.796,3.643,15.573,4.508   c6.176,1.114,9.973-0.919,14.751-3.277c-7.277-6.795-23.986-4.149-29.912-12.297c0.229-1.409,1.193-2.083,2.05-2.865   c-19.18,4.213-31.256-7.281-39.34-18.031c-23.662-6.112-44.421-15.133-54.504-34.831c-0.484-1.855,1.817-0.915,1.233-2.87   c-8.319-9.257-16.634-18.655-23.358-29.505c-2.324-3.746-3.915-8.454-6.558-11.473c-1.674-1.913-4.483-2.966-6.146-4.92   c-1.821-2.142-2.069-4.824-4.92-5.734c-1.096,1.634-0.361,5.098-1.227,6.965c-1.971-7.913-6.362-15.428-14.752-15.573   c-0.156-5.755,4.493-6.703,6.965-9.835c-3.254-3.913-4.038-8.841-5.736-14.75c-4.128-14.359-7.539-29.359-11.066-42.62   c-4.674,1.745-5.913,6.926-8.194,11.065c0.225-5.92,0.502-11.792,3.689-14.755c1.457,0.183,1.617,1.664,2.457,2.46   c0.77-2.792,3.412-5.396,2.048-9.014c-1.058-1.634-4.151-0.872-4.915-0.819C182.414,234.271,184.112,225.289,181.623,219.55z    M346.357,462.557c3.543-1.514,6.732-3.377,8.192-6.97C350.698,456.552,345.268,458.007,346.357,462.557z M346.765,454.36   c-2.37,1.313-5.036,2.341-6.554,4.508C343.608,459.071,347.588,455.661,346.765,454.36z M334.064,460.506   c2.32-0.619,4.803-3.015,4.508-4.919C335.878,455.857,331.711,457.778,334.064,460.506z M335.703,451.079   c-3.688-1.165-6.699,1.722-6.97,5.331C332.019,455.595,334.243,453.72,335.703,451.079z M324.226,451.902   c-3.602,0.628-6.296,2.162-7.377,5.323C321.252,458.972,323.506,455.188,324.226,451.902z M318.491,462.557   c1.015,0.058,1.987,0.074,2.05-0.823C319.926,461.084,318.204,461.134,318.491,462.557z M325.049,444.933   c-5.734-0.44-12.592,3.281-9.016,8.196C319.851,451.208,323.718,449.341,325.049,444.933z M296.771,452.722   c3.581,0.503,4.517-3.593,6.97-2.874c1.423,0.898,0.558,4.088,2.865,4.101c5.36-1.09,7.29-8.404,4.097-13.523   C303.479,441.697,296.87,445.673,296.771,452.722z M298.409,442.067c-2.175,1.102-4.491,2.059-5.734,4.096   C295.356,446.047,299.349,443.09,298.409,442.067z M286.94,444.117c0.229,1.09-1.688,2.084-0.416,2.865   C286.865,446.467,289.02,444.441,286.94,444.117z M279.563,453.948c-0.129,0.558-0.586,0.782-0.407,1.639c0.541,0,1.09,0,1.639,0   C280.906,454.514,280.64,453.827,279.563,453.948z M273.417,451.902c-2.071,0.116-2.854,1.518-2.87,3.685   C272.331,455.191,273.957,454.63,273.417,451.902z M232.024,431.001c-2.525-0.111-3.295,0.279-0.407,0.824   c2.751,0.507,7.604,0.773,9.426,0C238.88,431.8,233.291,431.06,232.024,431.001z M244.321,424.447   c-2.144-1.63-6.454-0.449-8.605,0.408C236.957,428.265,243.051,426.751,244.321,424.447z M231.21,455.179   c10.22,5.356,24.292,11.203,38.926,9.424C259.502,459.396,243.688,457.175,231.21,455.179z M216.046,450.671   c0.979,1.344,3.291,1.352,4.915,2.051C223.986,449.798,217.337,448.151,216.046,450.671z M177.525,417.478   c-2.766,0.241-5.776,0.233-6.556,2.462C173.604,420.917,177.417,420.31,177.525,417.478z M169.738,428.132   c0.963,0.873,2.734,1.913,3.279,0C172.593,427.699,170.092,427.288,169.738,428.132z M174.656,393.3   c0.372-1.713-2.891-2.361-3.277-0.818C172.277,392.946,173.055,393.537,174.656,393.3z M179.985,407.231   c-0.02-0.562,0.193-0.898,0.409-1.227c-1.221-1.261-3.69-1.485-5.738-0.819C174.984,407.156,178.266,407.979,179.985,407.231z    M180.395,433.463c0.524,0.558,1.934,0.558,2.458,0c0.193-1.289-0.512-1.676-1.229-2.054   C181.256,432.137,180.634,432.606,180.395,433.463z M193.099,386.335c-1.335-3.859-5.688-2.841-8.607-4.097   c-4.691-2.021-8.696-6.845-14.753-6.965c-0.272,0-0.547,0-0.817,0C174.19,381.481,181.162,388.152,193.099,386.335z    M171.788,371.177c-3.825-2.599-8.015-4.832-13.523-5.738C160.016,369.834,166.832,371.348,171.788,371.177z M184.491,390.431   c2.873,3.003,6.479,5.273,12.704,4.916C194.802,392.136,189.084,390.077,184.491,390.431z M200.063,408.874   c-4.219-2.924-10.855-7.668-16.391-6.559C186.874,406.491,193.311,409.618,200.063,408.874z M184.491,424.447   c-0.099,0.583-0.674,0.687-0.819,1.223C184.682,426.988,186.202,424.722,184.491,424.447z M193.916,436.74   c0.348,1.563,1.853,1.971,3.279,2.458c0.555-0.948,1.646-1.36,1.229-3.277C197.428,435.322,193.846,434.977,193.916,436.74z    M201.703,418.709c-1.269-0.777-5.897-1.646-6.968,0C196.723,419.516,200.628,421.604,201.703,418.709z M202.932,404.773   c0.41-3.048-3.038-3.061-4.508-2.05C198.562,404.773,201.274,404.25,202.932,404.773z M207.439,382.646   c-1.851-2.795-6.992-2.296-10.654-3.277c-2.682-3.368-9.095-4.591-14.752-3.688C188.512,379.997,195.881,383.415,207.439,382.646z    M206.62,421.985c1.76,1.519,4.519,2.038,6.966,2.87c0.131-0.965,0.646-1.539,0.409-2.87   C212.802,420.609,207.625,419.898,206.62,421.985z M171.788,355.599c0.41-1.912-0.715-2.287-2.459-2.046   C168.711,355.674,170.755,355.129,171.788,355.599z M181.623,360.519c-1.197-0.304-0.794-2.208-2.459-2.05   C177.654,359.854,180.374,361.962,181.623,360.519z M153.348,363.388c-1.36-3.007-4.425-4.316-6.556-6.558   c3.996-5.789-4.92-8.159-6.557-12.293c-0.019-1.247,0.865-1.593,1.229-2.462c-3.443-2.017-7.419-3.505-9.426-6.961   c1.585-1.147,5.81,0.341,7.375-0.823c-2.482-1.069-5.162-1.938-6.146-4.508c1.437-3.344,7.279-2.279,8.605-5.735   c-7.059-1.559-14.072-5.31-21.72-4.919c0.087,2.919,2.685,3.326,3.688,5.327c-2.267-1.007-4.101-2.458-7.375-2.458   c-0.245,2.021,1.064,2.487,0.821,4.508c-2.235,0.183-3.368-0.731-5.739-0.407c1.69,3.771,6.024,4.902,7.378,9.016   c-1.676,0.424-3.951-0.666-4.508,0c4.326,3.593,10.644,7.381,13.111,11.469c-4.025-0.748-6.329-3.227-10.242-4.096   c3.276,6.487,11.253,7.839,17.21,11.065C140.594,356.854,146.058,362.178,153.348,363.388z M144.332,368.304   c1.713,0.936,5.123,3.908,7.377,1.643C149.809,369.105,146.82,367.193,144.332,368.304z M141.055,366.253   c-1.153-1.867-7.036-2.861-8.604-1.639C135.125,365.384,137.645,367.459,141.055,366.253z M133.678,367.484   c-0.129,0.557-0.582,0.781-0.409,1.643c0.721-0.237,2.407,0.49,2.459-0.412C135.092,368.258,134.873,367.384,133.678,367.484z    M128.351,312.982c-1.118-3.851-2.611-8.071-5.736-11.062c-1.683-1.613-3.313-1.58-4.508-3.693   c-3.167-5.572-1.649-13.439-5.737-19.254c-0.967-0.315-2.832-0.811-3.688,0c0.077,2.687,6.313,9.058,2.051,12.293   c-9.424,0.374-13.052-7.128-22.128-5.739c-2.044,5.294,5.182,8.014,3.276,11.886C104.917,301.597,115.27,310.662,128.351,312.982z    M98.846,325.275c2.408,1.834,5.889,4.766,9.016,4.508C105.385,328.028,103.106,323.895,98.846,325.275z M94.338,321.591   c-1.063-3.307-2.906-5.835-6.966-6.146C88.198,318.987,92.047,319.512,94.338,321.591z M87.372,332.245   c2.194,1.501,4.373,5.181,6.557,5.327C92.332,335.48,90.386,331.559,87.372,332.245z M90.242,303.967   c0.212-0.607,0.604-1.031,0.819-1.639c-1.051-1.447-3.642-0.657-4.097,0.823C87.77,303.709,89.304,303.543,90.242,303.967z    M153.759,320.359c-0.058-3.526-3.975-5.572-6.967-3.685C147.74,319.278,150.597,319.969,153.759,320.359z M115.236,266.682   c0.069-0.678-2.523-0.678-2.457,0C113.341,266.806,115.251,268.532,115.236,266.682z M99.258,265.039c-0.547,0-1.094,0-1.641,0   c-0.563,0.527-0.405,1.784-0.41,2.865c0.749,0.112,2.298,1.48,2.87,0.415C99.063,267.962,100.195,265.467,99.258,265.039z    M68.521,264.627c1.358,3.09,6.855,2.861,7.787-0.407C73.976,263.317,70.541,263.945,68.521,264.627z M69.753,253.153   c-1.585-0.079-3.021-0.013-4.101,0.412C65.971,255.353,69.742,255.035,69.753,253.153z M73.439,187.18   c-2.106,0.973-6.498-0.975-8.604,0c1.865,7.383,15.688,3.408,14.753-2.46c-0.794-4.978-13.939-3.745-18.441-3.277   C64.636,183.963,70.182,184.427,73.439,187.18z M57.049,194.965c0.771,1.142,2.89,0.934,4.098,1.639   c0.237-0.854,1.017-1.168,0.819-2.458C60.891,193.578,57.023,193.131,57.049,194.965z M77.949,193.327   c-0.221,0.894-0.994,2.651,0.407,2.869C79.332,195.508,79.128,193.921,77.949,193.327z M89.423,168.739   c-0.108-1.198,0.925-1.256,0.819-2.458c-1.666-0.163-2.857,0.149-2.87,1.638C88.152,168.097,88.401,168.802,89.423,168.739z    M89.013,77.767c-1.632,10,7.378,22.097,18.029,18.439c0.497-3.774-1.225-5.329-1.229-8.604c2.718-0.659,4.318,1.951,5.736,1.229   C107.563,81.618,96.96,81.021,89.013,77.767z M84.503,68.342c3.602,0.713,9.255,0.352,10.656-2.459   C92.438,64.065,84.274,63.578,84.503,68.342z M74.668,39.656c0.788-7.959-8.938-12.357-14.75-6.965   c-3.633,3.368-5.211,11.502,0.409,14.343c-0.638-2.096-2.501-2.963-2.048-6.146C62.55,38.446,70.381,42.079,74.668,39.656z    M71.803,65.882c1.042-0.595,2.607-0.666,2.458-2.458C73.001,63.551,70.854,64.909,71.803,65.882z M63.195,96.206   c5.11,0.121,8.963-2.761,13.933-2.867c4.302-0.091,8.402,1.189,13.523,0.819C86.994,83.425,69.225,92.798,63.195,96.206z    M55.41,115.057c9.669-1.229,23.14-7.591,36.061-6.146c4.874,0.544,9.143,3.287,11.883,5.327c-1.397-1.491-3.052-7.61,0-8.604   c6.725,1.281,6.949,13.987,15.162,12.293c4.184-0.863,5.458-8.979,3.279-13.933c3.127,2.2,4.738,5.916,9.016,6.967   c-0.976-3.942-3.813-6.023-5.736-9.016c1.208-1.522,2.79-2.674,2.457-5.739c-11.727-1.127-22.136,5.203-33.193,7.377   c-8.581,1.69-14.967,3.364-22.535,5.327C66.114,110.385,59.783,111.42,55.41,115.057z M20.988,199.884   c-0.563,0.522-0.714,2.448,0.409,2.458C21.734,202.045,22.497,199.506,20.988,199.884z M35.328,151.12   c-17.969,2.851,1.184,21.961,11.886,17.212c1.355-2.081,0.934-3.988,0.819-6.97c6.235,0.611,10.926-2.426,16.393-1.227   c0.882,1.905-0.786,3.518-1.23,5.325c18.593-1.179,27.799-15.788,47.943-18.029c2.503-0.279,5.356,0.164,8.198,0   c8.483-0.495,17.88-2.067,26.636-3.689c8.591-1.588,16.446-4.747,23.766-6.554c9.187-2.271,23.163-8.271,21.311-20.491   c-0.212-1.391-1.177-2.641-2.05-4.098c-48.834-4.722-85.346,14.422-123.754,22.129c-4.614,0.925-10.224,0.31-13.934,4.096   c1.342,3.302,6.058,3.231,8.194,5.737c-1.068,1.252-3.709,0.932-4.096,2.87c0.904,3.466,6.042,2.694,6.556,6.558   c-8.157,5.75-25.261-1.584-21.309-13.114c-12.325,2.701-30.27,5.385-30.323,19.26c-0.025,6.115,3.62,11.771,7.784,15.162   C15.297,162.387,20.092,143.297,35.328,151.12z M50.492,227.749c0.373-2.775-4.188-4.718-5.736-2.867   C46.266,226.239,48.63,226.74,50.492,227.749z M36.149,233.076c2.898,10.076,3.841,22.113,11.474,27.456   C46.474,248.704,42.277,239.925,36.149,233.076z M53.36,222.422c1.276-5.785-7.211-8.051-7.785-4.099   C45.074,221.765,50.501,221.365,53.36,222.422z M55,211.356c-1.85-2.023-6.493-3.277-9.834-2.458   C46.345,211.799,53.599,216.092,55,211.356z M50.083,193.327c1.851-1.154,3.815-2.198,4.096-4.92   c-2.378-1.78-8.071-2.031-8.604,0.824C45.172,191.389,48.064,192.264,50.083,193.327z M55.41,200.292   c0.179-1.408-0.162-2.295-0.41-3.279c-2.102-0.052-3.083,1.015-3.278,2.871C52.742,200.228,53.917,200.419,55.41,200.292z    M26.725,198.244c-0.316-1.05-0.41-2.323-1.229-2.868C24.477,196.479,24.438,198.46,26.725,198.244z M30.823,170.38   c-1.839-0.717-4.561,0.048-5.327,1.638c0.86,0.776,2.098,1.181,3.278,1.637C29.188,172.299,31.041,172.374,30.823,170.38z    M35.328,223.241c-1.06-2.354-1.193-5.635-3.276-6.965C26.441,217.074,32,225.135,35.328,223.241z M43.115,267.496   c4.001,9.673,8.224,20.128,16.803,24.586c-6.415-7.137-7.929-18.946-12.295-27.455c-1.51-2.936-3.919-5.219-5.327-8.193   c-3.313-7.003-4.84-15.174-11.473-18.441C33.437,248.298,39.036,257.624,43.115,267.496z M155.808,421.167   c-2.48-8.446-9.137-12.722-18.441-14.343c-2.3-5.485-8.938-6.629-10.244-13.112c-0.212-1.331,2.538-1.801,1.641-2.458   c-12.472,2.362-12.912-10.857-18.851-16.393c-14.987,0.271-12.199-18.272-20.489-27.862c-2.368-2.744-4.716-3.377-7.377-6.146   c-4.095-12.691-14.782-19.129-20.899-30.323c-5.433-9.947-6.576-21.167-15.571-28.278c7.117,24.095,22.364,44.463,36.061,64.748   c10.964,16.23,18.42,31.688,30.733,44.663c4.184,4.403,8.908,7.352,13.934,11.473C134.854,410.146,140.741,423.15,155.808,421.167z    M154.167,393.3c-0.441-1.755-3.602-2.939-5.327-2.046C150.429,392.128,152.175,392.835,154.167,393.3z M169.329,382.646   c-2.776-3.235-8.588-4.467-13.932-6.555c-6.629-2.595-16.087-5.052-20.898-2.05c0.484,4.021,3.687,5.327,5.736,7.785   c5.693,0.877,8.951,3.655,14.341,4.096C160.929,386.447,166.862,386.164,169.329,382.646z M364.796,476.08   c-12.4-5.655-30.586,0.707-43.848-2.462c-2.503-0.599-4.716-2.32-6.965-2.458c-2.237-0.137-4.841,1.044-6.966,1.231   c-11.357,1.01-21.725-0.112-32.37-1.643c-7.469-1.073-15.424-1.493-22.132-3.277c-6.425-1.705-13.07-5.639-19.67-8.196   c-6.697-2.591-13.669-5.173-20.079-7.785c-12.646-5.152-26.086-14.068-39.34-17.619c8.941,9.498,24.334,12.55,34.834,20.489   c-14.838-4.15-26.034-11.939-39.34-17.62c10.367,9.282,24.833,14.904,39.34,20.896c14.447,5.972,30.146,11.024,47.122,13.523   C289.103,476.126,328.654,483.503,364.796,476.08z M375.45,474.849c-2.104,0.084-4.725-0.354-4.915,1.639   C372.318,478.018,375.317,477.859,375.45,474.849z M397.578,426.493c0.582,3.028,4.978,2.125,4.512-1.23   C399.856,424.946,398.888,425.895,397.578,426.493z M431.59,447.802c-11.016-0.266-24.605-4.071-36.063-3.685   c-4.396,0.146-9.739,1.198-11.062,5.73c3.381,1.372,7.003,0.549,11.062,0.416C408.818,449.814,425.058,455.786,431.59,447.802z    M442.656,446.982c-1.917-0.004-2.482,1.348-2.869,2.865c0.527,0.565,1.779,0.412,2.869,0.416   C442.461,448.45,443.218,448.222,442.656,446.982z M466.834,445.345c-2-0.304-2.745,2.183-2.05,3.28   c1.289,0.195,1.601-0.586,2.461-0.823C467.541,446.55,466.538,446.596,466.834,445.345z M500.843,447.802   c-8.389-0.894-18.186-0.341-25.813,0.823C479.521,452.854,495.652,450.155,500.843,447.802z M106.633,198.651   c4.042,2.246,7.772,6.978,13.114,6.558c-1.443-1.971-3.489-3.341-4.92-5.325c1.522-0.12,2.815-0.463,3.279-1.64   c-4.984-3.487-11.376-7.746-13.932-12.297C105.861,189.216,108.443,194.424,106.633,198.651z M159.086,201.933   c-0.877-0.898-0.482-3.073-1.641-3.688C157.184,200.028,158.338,202.521,159.086,201.933z M121.385,237.586   c0.628,6.747,4.94,9.806,5.327,16.8c-4.79-5.454-7.464-13.027-10.654-20.083c-0.313,8.535,2.267,13.823,4.508,19.674   c1.725,4.496,3.342,9.773,7.785,11.063c2.075-0.387,1.959-2.966,4.101-3.281c2.278,0.328,3.464,3.904,4.915,3.692   c-1.094-1.23-1.435-3.21-1.639-5.327c0.396-1.518,2.566-1.26,3.277-2.462C134.884,249.219,128.977,242.557,121.385,237.586z"></path>
</g>
</svg>

Here the icon! :)

**Comment by pheralb** [comment]
Ready 🫡
