### ISSUE TITLE
Improve logo search.

### ISSUE THREAD

**Issue by ByMykel** [pheralb/svgl#23]
A thought about improving the search alowing multiple words search.

For example if I search `open boot` it would give me 0 results but searching why words would give me 1 results.

![image](https://user-images.githubusercontent.com/38622893/194157079-92cc819d-11ce-428a-b084-6e767078c0a2.png)

Let me know if you like this feature and I can make a PR for hacktoberfest 😄 

Edit: update example

**Comment by pheralb** [comment]
No problem 🚀🚀
