### ISSUE TITLE
HuggingFace Logo

### ISSUE THREAD

**Issue by jovanlopez32** [pheralb/svgl#263]
## 🔎 Information:

- **Title**: HuggingFace
- **Category**: AI
- **Source (.svg)**: https://cdn-lfs.huggingface.co/repos/96/a2/96a2c8468c1546e660ac2609e49404b8588fcf5a748761fa72c154b2836b4c83/942cad1ccda905ac5a659dfd2d78b344fccfb84a8a3ac3721e08f488205638a0?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27hf-logo.svg%3B+filename%3D%22hf-logo.svg%22%3B&response-content-type=image%2Fsvg%2Bxml&Expires=1709362580&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwOTM2MjU4MH19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9yZXBvcy85Ni9hMi85NmEyYzg0NjhjMTU0NmU2NjBhYzI2MDllNDk0MDRiODU4OGZjZjVhNzQ4NzYxZmE3MmMxNTRiMjgzNmI0YzgzLzk0MmNhZDFjY2RhOTA1YWM1YTY1OWRmZDJkNzhiMzQ0ZmNjZmI4NGE4YTNhYzM3MjFlMDhmNDg4MjA1NjM4YTA%7EcmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj0qJnJlc3BvbnNlLWNvbnRlbnQtdHlwZT0qIn1dfQ__&Signature=AAhu1Apw4aPkGJfjDenYyDCTcrVORqtCuvmM1JC7nNicjOd6NupK4I1hQv95szvSbhIj5iHFEW7FJQNP3D%7E7oNXgUWgVzCkF%7EbYyvs5gbZDEQJACTeWX5KTLa2mzxB%7Eu5ArEcYSJAcOlY3StDLzMsZxPAlDQuj0KzaZ6yVU2MNncEWwv7%7ED7TB1rTOosQvIXh7KP166%7ExbtNGw1TykGFzDSvb4%7E7oHdtrl34JbJxdj9adfIDKPZ5LpDX33UJ9NzVLNPlhx49Rxy1Q5bQhIchnl-B8p17jA42qzAXdwLdnHDISZ87OthnmaWlB4x2WLylanicCpgD%7ExjaSmZ4C7lXIg__&Key-Pair-Id=KVTP0A1DKRTAX

- **Source 2 (.svg)**: https://cdn-lfs.huggingface.co/repos/96/a2/96a2c8468c1546e660ac2609e49404b8588fcf5a748761fa72c154b2836b4c83/fc95837e1bacb9b2cdbff9ae5d681ed8f20233b8fc72a65cdb38321ea9ddc015?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27hf-logo-with-title.svg%3B+filename%3D%22hf-logo-with-title.svg%22%3B&response-content-type=image%2Fsvg%2Bxml&Expires=1709362606&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwOTM2MjYwNn19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9yZXBvcy85Ni9hMi85NmEyYzg0NjhjMTU0NmU2NjBhYzI2MDllNDk0MDRiODU4OGZjZjVhNzQ4NzYxZmE3MmMxNTRiMjgzNmI0YzgzL2ZjOTU4MzdlMWJhY2I5YjJjZGJmZjlhZTVkNjgxZWQ4ZjIwMjMzYjhmYzcyYTY1Y2RiMzgzMjFlYTlkZGMwMTU%7EcmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj0qJnJlc3BvbnNlLWNvbnRlbnQtdHlwZT0qIn1dfQ__&Signature=motl3ZlSggqtvk%7En29OoKwpJM%7EBvYJsTFiXuTiTzNlIjFif-yFWlJ7qlnoFZw3uJnRmux5TluiHkVqK8FyXOaCSZw5kbAM0xLQtI4roZRK49AI1WD6SnQh3xA2QA5AHCbywGEA7ZfpFKdTi7XP1-cSDE7RjSE-9V-L8FKzMOSGE%7EMwL5vfzv3EEptkbnFO451chbW8uIKit4YYsQpiMw9YuAKSyDbi86mT3Y-s1W0sA7-POaiexqP9D9KgQwMb8FZs1--LSBZK3AkwwF6%7ET4HEXNnBJLkj1oKAgaHs9yG86OxktbG-G1TGRoZQvQjdMTd8iZ1gZoilIQ3WQDqMKaDQ__&Key-Pair-Id=KVTP0A1DKRTAX

- **Website**: https://huggingface.co/

## 📝 Checklist:

- [X] I have permission to use this logo.
- [x] The link I have provided is optimized for web use.
- [x] The size of the SVG is less than **20kb**.

**Comment by pheralb** [comment]
Ready 🚀
https://svgl.app/?search=hugging+face
