### ISSUE TITLE
🔔 [Request]: Mistral AI

### ISSUE THREAD

**Issue by jovanlopez32** [pheralb/svgl#264]
## 🔎 Information:

- **Title**: Mistral AI
- **Category**: AI
- **Source (.svg)**: https://docs.mistral.ai/img/logo.svg
- **Website**: https://mistral.ai/

## 📝 Checklist:

- [x] I have permission to use this logo.
- [x] The link I have provided is optimized for web use.
- [x] The size of the SVG is less than **20kb**.

**Comment by pheralb** [comment]
Ready 🚀
https://svgl.app/?search=mistral
