### ISSUE TITLE
[Request]:Blender icon

### ISSUE THREAD

**Issue by Fardeen-Awais** [pheralb/svgl#276]
## 🔎 Information:

- **Title**:
- **Category**:
- **Source (.svg)**:
- **Website**:

## 📝 Checklist:

- [x] I have permission to use this logo.
- [x] The link I have provided is optimized for web use.
- [x] The size of the SVG is less than **20kb**.

**Comment by roaming97** [comment]
Hey! The Blender logo has been added since https://github.com/pheralb/svgl/pull/334.
