### ISSUE TITLE
🔔 [Request]: Add Resend White icon

### ISSUE THREAD

**Issue by joaopcm** [pheralb/svgl#306]
## 🔎 Information:

- **Title**: Resend White
- **Category**: Software
- **Source (.svg)**: https://resend.com/static/brand/resend-icon-white.svg
- **Website**: https://resend.com/

## 📝 Checklist:

- [x] I have permission to use this logo.
- [x] The link I have provided is optimized for web use.
- [x] The size of the SVG is less than **20kb**.

**Comment by pheralb** [comment]
Ready 😊
