### ISSUE TITLE
🔔 [Request]: Add Google Drive icon

### ISSUE THREAD

**Issue by EnGassa** [pheralb/svgl#310]
## 🔎 Information:

- **Title**: Google Drive
- **Category**: Software
- **Source (.svg)**: https://upload.wikimedia.org/wikipedia/commons/1/12/Google_Drive_icon_%282020%29.svg
- **Website**: https://en.m.wikipedia.org/wiki/File:Google_Drive_icon_(2020).svg

## 📝 Checklist:

- [x] I have permission to use this logo.
- [x] The link I have provided is optimized for web use.
- [x] The size of the SVG is less than **20kb**.

**Comment by pheralb** [comment]
Ready 🚀
https://svgl.app/?search=google+drive
