### ISSUE TITLE
🔔 The svgl API might be unavailable.

### ISSUE THREAD

**Issue by pheralb** [pheralb/svgl#319]
Hi 👋,

Due to a recent DDoS attack, we've implemented protective measures, which might affect access to the API for some applications. However, our web app remains fully functional for everyone.

We expect to resolve the issue and restore normal API access within a few days.

We apologize for any inconvenience this may cause.

Best regards,
Pablo.

**Comment by ridemountainpig** [comment]
Hi @pheralb,

I have been using the SVGL API for my SVGL badge project. When retrieving SVGL data using the API on a GitHub Action, I'm encountering a `403 Client Error: Forbidden error for the URL "https://svgl.app/api/svgs"`. However, the API call is successful when running it locally. Is there an IP restriction in place for the SVGL API?

**Comment by ridemountainpig** [comment]
Hi @pheralb,

I have been using the SVGL API for my SVGL badge project. When retrieving SVGL data using the API on a GitHub Action, I'm encountering a `403 Client Error: Forbidden error for the URL ﻿"https://svgl.app/api/svgs"`. However, the API call is successful when running it locally. Is there an IP restriction in place for the SVGL API?

**Comment by pheralb** [comment]
Hi @ridemountainpig, 

The SVGL api, for security reasons, has a restriction and limit of request per minute.

I just accessed your project and at the moment the api returns the data, but I see that you are rendering the 400 logos directly. You can optimize it by adding a filter to show the last 15 logos:
```
/api/svgs?limit=15
```

Thanks 🚀

**Comment by ridemountainpig** [comment]
> Hi @ridemountainpig,
> 
> The SVGL api, for security reasons, has a restriction and limit of request per minute.
> 
> I just accessed your project and at the moment the api returns the data, but I see that you are rendering the 400 logos directly. You can optimize it by adding a filter to show the last 15 logos:
> 
> ```
> /api/svgs?limit=15
> ```
> 
> Thanks 🚀

Thank you for your reply. In the SVG badge project, I have saved all the SVG files to my repository, so the logos are not directly retrieved from the SVG API. I'm using the `https://svgl.app/api/svgs` API to get all the logo data, and I'm downloading it from the GitHub raw file to my project using a GitHub action. However, I'm now unable to access `https://svgl.app/api/svgs` with the GitHub action, so I'm trying to resolve this issue.
