### ISSUE TITLE
[BUG]: Next.js SVG for typescript throws error

### ISSUE THREAD

**Issue by Ansub** [pheralb/svgl#353]
So I was copying and pasting a Next.js TSX component and adding it to my codebase, but it started giving me an error. Prettier failed to format the code.

<img width="1145" alt="image" src="https://github.com/pheralb/svgl/assets/12985873/7647b02b-0b4a-410e-a59a-531189b2e67d">

The error came from the component name, which was named "next.js", causing the issue and removing the `.` fixes the issue

**Comment by pheralb** [comment]
Hi Ansub! 😊

Thank you for letting us know! I will fix it shortly.

**Comment by pheralb** [comment]
Fixed 🚀

**Comment by Ansub** [comment]
Perfect, thanks!
