### ISSUE TITLE
Python logo doesn't work well

### ISSUE THREAD

**Issue by HananGK** [pheralb/svgl#381]
When I try to add the Python logo to my code it appears of color green and only a corner is visible, must have an error on the code but I'm not able to resolve it. With the other logos I don't have any problem. Hope you can fix it, thanks.

**Comment by RatoGBM** [comment]
Python logo does have to much white space around it, a 16x16 logo was put into a 64x64 viewBox.

here is `test.html` I used for trying to replicate any issues.
```html
<html>
  <body>
    <img src='r.svg'/>
    <img src='python.svg'/>
    <img src='csharp.svg'/>
  </body>
</html>
```

There are lot's of tools for that like https://www.svgviewer.dev/. I will do it myself a bit later if I have time.

@HananGK, write better bug reports. You have an issue that is probably very specific to your code and situation, I have to blindly punch the logo into different situation and hope your issue shows up. Give as much information as you can about what you are doing and section of the code. Try to write a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) (causing the issue in as few lines of code as possible.)

**Comment by RatoGBM** [comment]
Yeah, python logo had it's size set to 2500x2500 and a way to large viewBox. Here is a fixed version, I removed the dimensions entirely, and set `viewBox="16 16 32 32"`. Dirty but works.
![python](https://github.com/user-attachments/assets/121abe0c-e17a-46ee-92e4-b6883ed6c225)

**Comment by pheralb** [comment]
Fixed 🚀
https://github.com/pheralb/svgl/commit/6ad19d71f48aa34ebddae8ae1418ac1b607d6903
