### ISSUE TITLE
[Request]: Polars

### ISSUE THREAD

**Issue by baggiponte** [pheralb/svgl#393]
## 🔎 Information:

> **All fields are required**:

- **Title**: Polars: DataFrames for the new era
- **Category** ([check categories](https://github.com/pheralb/svgl/blob/main/src/types/categories.ts#L1)): Not really a database, it's a Python library to manipulate data, a bit like duckdb.
- **Source (.svg)** (type the link of the svg): https://raw.githubusercontent.com/pola-rs/polars-static/master/logos/polars_logo_blue.svg
- **Company/Product Website**: pola.rs

## 📝 Checklist:

> **Make sure that you have completed the following steps**:

- [x] I have permission to use this logo.
- [x] The link I have provided is optimized for web use.
- [x] The size of the SVG is less than **20kb**.

**Comment by atleugim** [comment]
I added a PR with this logo request: https://github.com/pheralb/svgl/pull/452

**Comment by pheralb** [comment]
Ready 🚀
https://svgl.app/?search=polars
