### ISSUE TITLE
🔔 [Request]: Add Soundcloud icon

### ISSUE THREAD

**Issue by yoperez** [pheralb/svgl#397]
## 🔎 Information:

- **Title**: Soundcloud
- **Category**: Music
- **Source (.svg)**: https://www.svgrepo.com/download/21451/soundcloud.svg
- **Website**: https://soundcloud.com/

## 📝 Checklist:

- [x] I have permission to use this logo.
- [x] The link I have provided is optimized for web use.
- [x] The size of the SVG is less than **20kb**.

**Comment by atleugim** [comment]
I added a PR for this logo request: https://github.com/pheralb/svgl/pull/454

**Comment by pheralb** [comment]
Ready 🚀
https://svgl.app/?search=soundcloud
