### ISSUE TITLE
🔔 [Request]: Add Google Colaboratory icon

### ISSUE THREAD

**Issue by cyrildiagne** [pheralb/svgl#400]
## 🔎 Information:

- **Title**: Google Colaboratory
- **Category**: AI
- **Source (.svg)**: https://upload.wikimedia.org/wikipedia/commons/d/d0/Google_Colaboratory_SVG_Logo.svg
- **Website**: https://colab.research.google.com/

## 📝 Checklist:

- [x] I have permission to use this logo.
- [x] The link I have provided is optimized for web use.
- [x] The size of the SVG is less than **20kb**.

**Comment by pheralb** [comment]
Ready 🚀
- https://github.com/pheralb/svgl/commit/3b88bc83c2c660fdb9ee849debd220705cc7b02c
