### ISSUE TITLE
[Request]: Add Raspberry Pi logo

### ISSUE THREAD

**Issue by eamartin96** [pheralb/svgl#401]
## 🔎 Information:

> **All fields are required**:

- **Title**: Raspberry Pi
- **Category**: Software
- **Source (.svg)**: https://upload.wikimedia.org/wikipedia/en/c/cb/Raspberry_Pi_Logo.svg
- **Company/Product Website**: https://www.raspberrypi.com/

## 📝 Checklist:

> **Make sure that you have completed the following steps**:

- [x] I have permission to use this logo.
- [x] The link I have provided is optimized for web use.
- [x] The size of the SVG is less than **20kb**.

**Comment by pheralb** [comment]
Ready 🚀
- https://svgl.app/?search=raspberry
- https://github.com/pheralb/svgl/commit/575d483cf60599b88cabfa0dd616a40fdb6eb92f
