### ISSUE TITLE
🔔 [Request]: Add Carrd icon

### ISSUE THREAD

**Issue by alxandrws** [pheralb/svgl#416]
## 🔎 Information:

- **Title**: Carrd
- **Category**: Software
- **Source (.svg)**: https://carrd.co/assets/docs/images/brand/svg/icon-color.svg
- **Website**: https://carrd.co/

## 📝 Checklist:

- [x] I have permission to use this logo.
- [x] The link I have provided is optimized for web use.
- [x] The size of the SVG is less than **20kb**.

**Comment by pheralb** [comment]
Ready 🚀
https://github.com/pheralb/svgl/commit/bf6aa58ac0fac0ae610d5db55f2d8693a06b1161
