### ISSUE TITLE
[🔔 Request SVG]: daily.dev logo

### ISSUE THREAD

**Issue by atybdot** [pheralb/svgl#437]
### Title

daily.dev

### SVG URL

https://drive.google.com/drive/folders/1GQ_jeQ4bgJOXoEqhu0JYqGKGwGAJUdJq

### SVG Dark Mode URL (optional)

https://drive.google.com/drive/folders/1GQ_jeQ4bgJOXoEqhu0JYqGKGwGAJUdJq

### Product URL

https://daily.dev/

### Category

Social, Community

### Checklist

- [X] I have permission to use this logo.
- [X] The .svg URL I have provided is optimized for web use.
- [X] The .svg size is less than **20kb**.

**Comment by atleugim** [comment]
I added a PR with this logo request: https://github.com/pheralb/svgl/pull/447

**Comment by atybdot** [comment]
thanks, i'll close it then.
