### ISSUE TITLE
[🚧 Bug]: Twitch logo React(TSX)

### ISSUE THREAD

**Issue by DiegoDev2** [pheralb/svgl#480]
![Screen Shot 2024-12-21 at 1 54 26 AM](https://github.com/user-attachments/assets/0378805a-b8d9-4b52-a940-8a9cf40f3cb4)

[twitch logo](https://svgl.app/?search=twitch)

**Comment by atleugim** [comment]
@DiegoDev2 You can check again the icon in the [app](https://svgl.app/?search=twitch) so @pheralb close the issue
