### ISSUE TITLE
Can't copy to clipboard in Safari

### ISSUE THREAD

**Issue by hodeinavarro** [pheralb/svgl#6]
Safari version: Versión 15.5 (17613.2.7.1.8)

```
Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
```

Seems to be a permission error... I have all default permissions and then also tested making svgl.vercel.app to have all of them in allowed.

I've been looking and found [this stackoverflow answer](https://stackoverflow.com/a/62566097/19123189) pointing to [this](https://webkit.org/blog/10247/new-webkit-features-in-safari-13-1/)

> ## Async Clipboard API
> 
> WebKit brings the Async Clipboard API to this release of Safari. It provides access to the system clipboard and clipboard operations while keeping the webpage responsive. This API is much more flexible than DataTransfer, allowing developers to write multiple items with multiple types per item. Additionally, it brings programmatic paste to all websites on macOS and iOS.
> 
> The implementation is available through the navigator.clipboard API which must be called within user gesture event handlers like pointerdown or pointerup, and only works for content served in a secure context (e.g. https://). Instead of a permissions-based model for reading from the clipboard, a native UI is displayed when the page calls into the clipboard API; the clipboard can only be accessed if the user then explicitly interacts with the platform UI.

TL:DR; 

> Instead of a permissions-based model for reading from the clipboard, a native UI is displayed when the page calls into the clipboard API; the clipboard can only be accessed if the user then explicitly interacts with the platform UI.

But looking at the code I can't see a good reason explaining why this is happening...
```typescript
const copyToClipboard = (url?: string) => {
  fetch(url || "").then((response) => {
    response.text().then((content) => {
      navigator.clipboard.writeText(content);
      toast("Copied to clipboard", ToastTheme);
    });
  });
};

/* ... */

<Button
    variant="ghost"
    borderWidth="1px"
    leftIcon={<Copy />}
    onClick={() => copyToClipboard(props.slug)}
    mb={{ base: "2", md: "0" }}
    mr={{ base: "0", md: "3" }}
    >
    Copy to clipboard
</Button>
```

EDIT: Forgot to add the error lol

**Comment by pheralb** [comment]
🤔 Thanks for reporting the error, I will leave the issue open while I fix the problem.

**Comment by d3vcloud** [comment]
I made a PR #14 for this issue.
