### ISSUE TITLE
Can we get all of this logo in this website?

### ISSUE THREAD

**Issue by utsavsomaiya** [pheralb/svgl#70]
<img width="1348" alt="image" src="https://github.com/pheralb/svgl/assets/96036522/bb1b1540-ac46-4f3b-8f93-2e1c07992a1e">

**Comment by steven-tey** [comment]
maybe via an NPM package / API? 👀

**Comment by utsavsomaiya** [comment]
Yeah, that also works!!

I don't know the any package!! Can you suggest me?
