### ISSUE TITLE
Create a new category : Community

### ISSUE THREAD

**Issue by advaith-unnikrishnan** [pheralb/svgl#73]
I noticed that Google Developer Students Club is listed in the education category, even though it is a community. It would be great if you could add the category "community" so that if someone uploads logos of communities, they can be displayed separately in that category.
![svgl](https://github.com/pheralb/svgl/assets/45172876/95dfc2c2-92ab-41dc-adb1-d3662166cf54)

**Comment by pheralb** [comment]
Ready, the new version will be published soon 🙂🚀
![image](https://github.com/pheralb/svgl/assets/62877300/7c947027-e7f4-4ba2-abd7-949c2baba64b)
