### ISSUE TITLE
🚀 Next updates.

### ISSUE THREAD

**Issue by pheralb** [pheralb/svgl#83]
I will work on the following features to improve the app:

- [x] Fix sidebar scroll bug for medium sizes.
- [x] Create API routes to get all svgs & categories.
- [x] Sticky search bar when scroll.
- [x] Add light/dark mode for scrollbar.
- [x] Improve app performance to avoid loading 200 svgs directly.

🚀🚀

**Comment by pheralb** [comment]
A new version of SVGL will be available soon ✨

**Comment by manish2022-creator** [comment]
Does all the tasks has been completed or anyone is remaining among this if yes then i will be very glad to work with collaborations.

**Comment by pheralb** [comment]
I am preparing Svgl v4, soon it will be available with all tasks solved 🙂
